### ISSUE TITLE
Fixes to to impress interviewers

### ISSUE THREAD

**Issue by melchior-by** [Ars199/Person2#1]
1. Create 2 comparators - for name and for age, and use both of them
2. Rename CustomComparator - we should know from it's name what it doing
3. Rename Person2 - we shouldn't use numbers in classes' names if it possible

**Comment by Ars199** [comment]
1. Code for name or age added. We cannot use both filters, as there must be ascending order of users
2. renamed
3. renamed

**Comment by melchior-by** [comment]
1. we can
